import React from 'react';
import './Styles/globals.css'; // Ruta corregida

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Puedes agregar más elementos <head> aquí si es necesario */}
      </head>
      <body>{children}</body>
    </html>
  )
}
