// src/app/layout.tsx
import React from 'react';
import Header from './Viuw/Components/Header/Header';
import Footer from './Viuw/Components/Footer/Footer';
import './Styles/globals.css';
import { UserChannelsSheet } from './Viuw/Components/ShowFollowChannels/UserChannelsSheet';
import RouteProgress from './Utils/LinksNavigation/RouteProgress';
import { TokenProvider } from './Controller/Context/UserContext';
import { ProfileUpdateProvider } from './Controller/Context/ProfileUpdateContext';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <ProfileUpdateProvider>
        <TokenProvider>
          <Header />

          <RouteProgress />

          <div className="mx-[100px]">{children}</div>

          <Footer />
        </TokenProvider>
        </ProfileUpdateProvider>
      </body>
    </html>
  );
}
